name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout library
        uses: actions/checkout@v3
      - name: Print Hello World
        run: echo "Hello World!"
      - name: Tell me the directory i am in
        run: pwd
      - name: who am i
        run: whoami
      - name: print out the data inside simple.txt
        run : cat simple.txt
